dark light theme portfolio page
Alcladii/crypto-app pull request #60
Opened 2024-04-12 20:25 UTC by Alcladii

2024-04-12 21:46 UTC, yoloOnTheBattlefield requested changes

2024-04-12 21:46 UTC, yoloOnTheBattlefield commented on src/components/PortfolioItem.jsx
> +          >
you forgot the key

2024-04-14 11:52 UTC, Basiol97 approved these changes

2024-04-14 11:53 UTC, Basiol97 requested changes
Follow Cris advice

2024-04-14 18:50 UTC, Alcladii commented
> Follow Cris advice

I've already added the key in accordance with his comments

2024-04-14 21:14 UTC, merged